#
# Configuration file for ladim
#
# Line source example
#

#version = "2.0"
version = 2.0  # Denne blir likt

[time]
    start = 1989-05-24 12:00:00
    stop = 1989-06-20T12:00:00
    reference =  1970-01-01 00:00:00
    dt =  [1, "h"]

[forcing]
    module = "ladim.ROMS"
    filename =  "../data/ocean_avg_0014.nc"

[tracker]
    advection = "EF"

[release]
    release_file = "line.rls"

[output]
    module = "ladim.out_netcdf"
    filename = "out.nc"
    output_period = [3, "h"]
    [output.ncargs]
        data_model = "NETCDF3_CLASSIC"
    [output.instance_variables]
        [output.instance_variables.pid]
            encoding = {datatype= "i4", zlib = true}
            attributes = {long_name = "particle_identifier"}
        [output.instance_variables.X]
            encoding = {datatype = "f4", zlib = true}
            attributes = {long_name = "particle X-coordinate"}
        [output.instance_variables.Y]
            encoding = {datatype = "f4", zlib =  true}
            attributes = {long_name = "particle Y-coordinate"}
        [output.instance_variables.Z]
            encoding = {datatype = "f4", zlib = true}
            [output.instance_variables.Z.attributes]
                long_name = "particle depth"
                standard_name = "depth_below_surface"
                units = "m"
                positive = "down"
    [output.global_attributes]
        title = "LADiM line example"
        institution = "Institute of Marine Research"
